apiVersion : apps/v1
kind: Deployment
metadata:
  name: ai-goap-logic 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-goap-logic 
  template:
    metadata:
      labels:
        app: ai-goap-logic 
    spec:
      containers:
        - name: ai-goap-logic
          env:
            - name: PORT
              value: "#{PORT}#"
            - name: SERVICE_ID
              value: "#{SERVICE_ID}#" 
            - name: CKG_ENDPOINT_URL
              value: "#{CKG_ENDPOINT_URL}#"
            - name: REACT_APP_PORTAL_AUTH_PROVIDER
              value: "#{REACT_APP_PORTAL_AUTH_PROVIDER}#"
            - name: REACT_APP_AUTH_AUDIENCE
              value: "#{REACT_APP_AUTH_AUDIENCE}#"
            - name: REACT_APP_PORTAL_AUTH_IDENTIFIER
              value: "#{REACT_APP_PORTAL_AUTH_IDENTIFIER}#"
            - name: REACT_APP_PORTAL_AUTH_CLIENT_ID
              value: "#{REACT_APP_PORTAL_AUTH_CLIENT_ID}#"
            - name: REACT_APP_PORTAL_AUTH_DOMAIN
              value: "#{REACT_APP_PORTAL_AUTH_DOMAIN}#"
            - name: REACT_APP_PORTAL_AUTH_CLIENT_SECRET
              value: "#{REACT_APP_PORTAL_AUTH_CLIENT_SECRET}#"
            - name: MAINTENANCE_SECRET
              value: "#{MAINTENANCE_SECRET}#"
            - name: VERSION_TAG
              value: "#{VERSION_TAG}#"
          image: services.azurecr.io/ai-goap-logic
          ports:
          - containerPort: 8050